name: "pipelinewerks"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  pipelinewerks:
    staging:
      +materialized: view
    marts:
      +materialized: table
