name: "real_time_project"
version: "1.0.0"
config-version: 2

profile: "default"

model-paths: ["models"]
macro-paths: ["macros"]

models:
  real_time_project:
    staging:
      +materialized: view
    marts:
      +materialized: table