
version: 2

models:
    - name: products
      description: "products details"
      columns:
          - name: product_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: product_name
            description: "The name of the product"
